# config file version
apiVersion: 1

datasources:
# Prometheus
- name: prom-direct
  type: prometheus
  access: proxy
  orgId: 1
  uid: ds_prom_direct
  url: http://prometheus:9090
  version: 1
  editable: true
- name: prom-trickster-memory-stdout
  type: prometheus
  access: proxy
  orgId: 1
  uid: ds_prom1_trickster
  url: http://trickster:8480/prom1
  version: 1
  editable: true
- name: prom-trickster-filesystem-jc
  type: prometheus
  access: proxy
  orgId: 1
  uid: ds_prom2_trickster
  url: http://trickster:8480/prom2
  version: 1
  editable: true
# Mockster (Prom API Simulator)
- name: sim-direct
  type: prometheus
  access: proxy
  orgId: 1
  uid: ds_sim_direct
  url: http://mockster:8482/prometheus
  version: 1
  editable: true
- name: sim-trickster-memory-ja
  type: prometheus
  access: proxy
  orgId: 1
  uid: ds_sim1_trickster
  url: http://trickster:8480/sim1
  version: 1
  editable: true
- name: sim-trickster-redis-ja
  type: prometheus
  access: proxy
  orgId: 1
  uid: ds_sim2_trickster
  url: http://trickster:8480/sim2
  version: 1
  editable: true
# InfluxDB
  # <string, required> name of the datasource. Required
- name: LocalInflux
  # <string, required> datasource type. Required
  type: influxdb
  # <string, required> access mode. proxy or direct (Server or Browser in the UI). Required
  access: proxy
  # <int> org id. will default to orgId 1 if not specified
  orgId: 1
  # <string> url
  url: http://influxdb-server:8086
  # <string> database password, if used
  password:
  # <string> database user, if used
  user:
  # <string> database name, if used
  database: inspectit
  # <bool> enable/disable basic auth
  basicAuth:
  # <string> basic auth username
  basicAuthUser:
  # <string> basic auth password
  basicAuthPassword:
  # <bool> enable/disable with credentials headers
  withCredentials:
  # <bool> mark as default datasource. Max one per org
  isDefault:
  # <map> fields that will be converted to json and stored in jsonData
  #jsonData:
  #   graphiteVersion: "1.1"
  #   tlsAuth: true
  #   tlsAuthWithCACert: true
  # <string> json object of data that will be encrypted.
  secureJsonData:
    tlsCACert: "..."
    tlsClientCert: "..."
    tlsClientKey: "..."
  version: 1
  # <bool> allow users to edit datasources from the UI.
  editable: false
