version: '3.8'
services:

  # InspectIT
  # ============================================================================
  # Agent
  agent:
    build: ./docker/agent
    image: inspectit/inspectit-agent
    container_name: inspectit-agent
    volumes:
      - agent-vol:/agent

  # Config server
  ocelot-config-server:
    image: inspectit/inspectit-ocelot-configurationserver:${INSPECTIT_OCELOT_VERSION}
    container_name: ocelot-config-server
    environment:
      - INSPECTIT_CONFIG_SERVER_WORKING_DIRECTORY=/configuration-server
      - INSPECTIT_CONFIG_SERVER_DEFAULT_USER_PASSWORD=demo
    volumes:
      - ./docker/configuration-server:/configuration-server
    networks:
      - trk-ex-front-tier
      - trk-ex-back-tier
    ports:
      - 8090:8090

  # Infrastructure
  # ============================================================================
  # Config server
  config-server:
    image: trickster/spring-petclinic-config-server
    container_name: trickster-config-server
    environment:
      - INSPECTIT_SERVICE_NAME=config-server
      - INSPECTIT_CONFIG_HTTP_URL=http://ocelot-config-server:8090/api/v1/agent/configuration
      - INSPECTIT_EXPORTERS_METRICS_PROMETHEUS_ENABLED=false
      - INSPECTIT_EXPORTERS_METRICS_INFLUX_URL=http://influxdb-server:8086
      - INSPECTIT_EXPORTERS_TRACING_ZIPKIN_URL=http://zipkin-server:9411/api/v2/spans
    depends_on:
      - agent
      - ocelot-config-server
    entrypoint: ["sh", "-c","
      ./dockerize -wait=tcp://ocelot-config-server:8090 \
                  -timeout=300s -- &&
      java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Djava.security.egd=file:/dev/./urandom
      -javaagent:/agent/inspectit-ocelot-agent.jar
      -jar /app.jar"]
    volumes:
      - agent-vol:/agent
    networks:
      - trk-ex-front-tier
      - trk-ex-back-tier
    ports:
      - 8888:8888

  # Discovery service
  discovery-server:
    image: trickster/spring-petclinic-discovery-server
    container_name: trickster-discovery-server
    environment:
      - INSPECTIT_SERVICE_NAME=discovery-server
      - INSPECTIT_CONFIG_HTTP_URL=http://ocelot-config-server:8090/api/v1/agent/configuration
      - INSPECTIT_EXPORTERS_METRICS_PROMETHEUS_ENABLED=false
      - INSPECTIT_EXPORTERS_METRICS_INFLUX_URL=http://influxdb-server:8086
      - INSPECTIT_EXPORTERS_TRACING_ZIPKIN_URL=http://zipkin-server:9411/api/v2/spans
    depends_on:
      - config-server
      - ocelot-config-server
      - agent
    entrypoint: ["sh", "-c","
      ./dockerize -wait=tcp://config-server:8888 \
                  -wait=tcp://ocelot-config-server:8090 \
                  -timeout=300s -- &&
      java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Djava.security.egd=file:/dev/./urandom
      -javaagent:/agent/inspectit-ocelot-agent.jar
      -jar /app.jar"]
    volumes:
      - agent-vol:/agent
    networks:
      - trk-ex-front-tier
      - trk-ex-back-tier
    ports:
      - 8761:8761

  # Services
  # ============================================================================
  # Customers service
  customers-service:
    image: trickster/spring-petclinic-customers-service
    container_name: trickster-customers-service
    environment:
      - INSPECTIT_SERVICE_NAME=customers-service
      - INSPECTIT_CONFIG_HTTP_URL=http://ocelot-config-server:8090/api/v1/agent/configuration
      - INSPECTIT_EXPORTERS_METRICS_PROMETHEUS_ENABLED=false
      - INSPECTIT_EXPORTERS_METRICS_INFLUX_URL=http://influxdb-server:8086
      - INSPECTIT_EXPORTERS_TRACING_ZIPKIN_URL=http://zipkin-server:9411/api/v2/spans
    depends_on:
      - config-server
      - ocelot-config-server
      - discovery-server
      - agent
    entrypoint: ["sh", "-c","
      ./dockerize -wait=tcp://discovery-server:8761 \
                  -wait=tcp://ocelot-config-server:8090 \
                  -timeout=300s -- &&
      java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Djava.security.egd=file:/dev/./urandom
      -javaagent:/agent/inspectit-ocelot-agent.jar
      -jar /app.jar"]
    volumes:
      - agent-vol:/agent
    networks:
      - trk-ex-front-tier
      - trk-ex-back-tier
    ports:
      - 8081:8081

  # Visits service
  visits-service:
    image: trickster/spring-petclinic-visits-service
    container_name: trickster-visits-service
    environment:
      - INSPECTIT_SERVICE_NAME=visits-service
      - INSPECTIT_CONFIG_HTTP_URL=http://ocelot-config-server:8090/api/v1/agent/configuration
      - INSPECTIT_EXPORTERS_METRICS_PROMETHEUS_ENABLED=false
      - INSPECTIT_EXPORTERS_METRICS_INFLUX_URL=http://influxdb-server:8086
      - INSPECTIT_EXPORTERS_TRACING_ZIPKIN_URL=http://zipkin-server:9411/api/v2/spans
    depends_on:
      - config-server
      - ocelot-config-server
      - discovery-server
      - agent
    entrypoint: ["sh", "-c","
      ./dockerize -wait=tcp://discovery-server:8761 \
                  -wait=tcp://ocelot-config-server:8090 \
                  -timeout=300s -- &&
      java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Djava.security.egd=file:/dev/./urandom
      -javaagent:/agent/inspectit-ocelot-agent.jar
      -jar /app.jar"]
    volumes:
      - agent-vol:/agent
    networks:
      - trk-ex-front-tier
      - trk-ex-back-tier
    ports:
      - 8082:8082

  #Vets service
  vets-service:
    image: trickster/spring-petclinic-vets-service
    container_name: trickster-vets-service
    environment:
      - INSPECTIT_SERVICE_NAME=vets-service
      - INSPECTIT_CONFIG_HTTP_URL=http://ocelot-config-server:8090/api/v1/agent/configuration
      - INSPECTIT_EXPORTERS_METRICS_PROMETHEUS_ENABLED=false
      - INSPECTIT_EXPORTERS_METRICS_INFLUX_URL=http://influxdb-server:8086
      - INSPECTIT_EXPORTERS_TRACING_ZIPKIN_URL=http://zipkin-server:9411/api/v2/spans
    depends_on:
      - config-server
      - ocelot-config-server
      - discovery-server
      - agent
    entrypoint: ["sh", "-c","
      ./dockerize -wait=tcp://discovery-server:8761 \
                  -wait=tcp://ocelot-config-server:8090 \
                  -timeout=300s -- &&
      java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Djava.security.egd=file:/dev/./urandom
      -javaagent:/agent/inspectit-ocelot-agent.jar
      -jar /app.jar"]
    volumes:
      - agent-vol:/agent
    networks:
      - trk-ex-front-tier
      - trk-ex-back-tier
    ports:
      - 8083:8083

  # API gateway
  api-gateway:
    image: trickster/spring-petclinic-api-gateway
    container_name: trickster-api-gateway
    environment:
      - INSPECTIT_SERVICE_NAME=api-gateway
      - INSPECTIT_CONFIG_HTTP_URL=http://ocelot-config-server:8090/api/v1/agent/configuration
      - INSPECTIT_EXPORTERS_METRICS_PROMETHEUS_ENABLED=false
      - INSPECTIT_EXPORTERS_METRICS_INFLUX_URL=http://influxdb-server:8086
      - INSPECTIT_EXPORTERS_TRACING_ZIPKIN_URL=http://zipkin-server:9411/api/v2/spans
    depends_on:
      - config-server
      - ocelot-config-server
      - discovery-server
      - agent
    entrypoint: ["sh", "-c","
      ./dockerize -wait=tcp://discovery-server:8761 \
                  -wait=tcp://ocelot-config-server:8090 \
                  -timeout=300s -- &&
      java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Djava.security.egd=file:/dev/./urandom
      -javaagent:/agent/inspectit-ocelot-agent.jar
      -jar /app.jar"]
    volumes:
      - agent-vol:/agent
    networks:
      - trk-ex-front-tier
      - trk-ex-back-tier
    ports:
      - 8080:8080

  # Admin Server
  # ============================================================================
  admin-server:
    image: trickster/spring-petclinic-admin-server
    container_name: trickster-admin-server
    environment:
      - INSPECTIT_SERVICE_NAME=admin-server
      - INSPECTIT_CONFIG_HTTP_URL=http://ocelot-config-server:8090/api/v1/agent/configuration
      - INSPECTIT_EXPORTERS_METRICS_PROMETHEUS_ENABLED=false
      - INSPECTIT_EXPORTERS_METRICS_INFLUX_URL=http://influxdb-server:8086
      - INSPECTIT_EXPORTERS_TRACING_ZIPKIN_URL=http://zipkin-server:9411/api/v2/spans
    depends_on:
     - config-server
     - ocelot-config-server
     - discovery-server
     - agent
    entrypoint: ["sh", "-c","
      ./dockerize -wait=tcp://config-server:8888 \
                  -wait=tcp://ocelot-config-server:8090 \
                  -timeout=300s -- &&
      java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Djava.security.egd=file:/dev/./urandom
      -javaagent:/agent/inspectit-ocelot-agent.jar
      -jar /app.jar"]
    volumes:
      - agent-vol:/agent
    networks:
      - trk-ex-front-tier
      - trk-ex-back-tier
    ports:
     - 9091:9090

  # Circuit breaker
  # ============================================================================
  # Hystrix dashboard:
  hystrix-dashboard:
    image: trickster/spring-petclinic-hystrix-dashboard
    container_name: trickster-hystrix-dashboard
    environment:
      - INSPECTIT_SERVICE_NAME=hystrix-dashboard
      - INSPECTIT_CONFIG_HTTP_URL=http://ocelot-config-server:8090/api/v1/agent/configuration
      - INSPECTIT_EXPORTERS_METRICS_PROMETHEUS_ENABLED=false
      - INSPECTIT_EXPORTERS_METRICS_INFLUX_URL=http://influxdb-server:8086
      - INSPECTIT_EXPORTERS_TRACING_ZIPKIN_URL=http://zipkin-server:9411/api/v2/spans
    depends_on:
     - config-server
     - ocelot-config-server
     - discovery-server
     - agent
    entrypoint: ["sh", "-c","
      ./dockerize -wait=tcp://config-server:8888 \
                  -wait=tcp://ocelot-config-server:8090 \
                  -timeout=300s -- &&
      java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Djava.security.egd=file:/dev/./urandom
      -javaagent:/agent/inspectit-ocelot-agent.jar
      -jar /app.jar"]
    volumes:
      - agent-vol:/agent
    networks:
      - trk-ex-front-tier
      - trk-ex-back-tier
    ports:
     - 7979:7979

  # Load
  # ============================================================================
  # Load server
  load-server:
    build: ./docker/load-server
    image: trickster/load-server
    container_name: trickster-load-server
    depends_on:
      - api-gateway
      - customers-service
      - visits-service
      - vets-service
    networks:
      - trk-ex-front-tier
      - trk-ex-back-tier

volumes:
  agent-vol:

networks:
  trk-ex-front-tier:
    external: true
  trk-ex-back-tier:
    external: true
