version: '3.8'
services:

  # Metrics
  # ============================================================================
  # InfluxDB
  influxdb-server:
    image: influxdb:1.7.1
    container_name: trickster-influxdb-server
    environment:
      - INFLUXDB_HTTP_FLUX_ENABLED=true
      - INFLUXDB_HTTP_LOG_ENABLED=false
      - INFLUXDB_DATA_QUERY_LOG_ENABLED=false
    volumes:
      - ./docker/influxdb-server:/docker-entrypoint-initdb.d
    networks:
      - trk-ex-back-tier
    ports:
      - 8086:8086

  # Chronograf
  chronograf:
    image: chronograf:1.6.2
    container_name: trickster-chronograf
    environment:
      INFLUXDB_URL: http://influxdb-server:8086
    networks:
      - trk-ex-back-tier
    ports:
      - 8889:8888

  # Trazing
  # ============================================================================
  # Zipkin server
  zipkin-server:
   image: openzipkin/zipkin:latest
   container_name: trickster-zipkin-server
   restart: always
   networks:
     - trk-ex-back-tier
   ports:
    - 9411:9411

networks:
  trk-ex-front-tier:
    external: true
  trk-ex-back-tier:
    external: true
