version: '3.8'
services:

  # Metrics
  # ============================================================================
  # Grafana
  grafana-direct:
    image: grafana/grafana:6.7.3
    container_name: trickster-grafana-direct
    restart: always
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./docker/grafana/direct/grafana-config:/etc/grafana
      - ./docker/grafana/direct/dashboards:/var/lib/grafana/dashboards
    networks:
      - trk-ex-front-tier
      - trk-ex-back-tier
    ports:
      - 3000:3000

networks:
  trk-ex-front-tier:
    external: true
  trk-ex-back-tier:
    external: true
