version: '3.8'
services:

  # Metrics
  # ============================================================================
  # Grafana
  grafana-mem:
    image: grafana/grafana:6.7.3
    container_name: trickster-grafana-mem
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./docker/grafana/mem/grafana-config:/etc/grafana
      - ./docker/grafana/mem/dashboards:/var/lib/grafana/dashboards
    networks:
      - trickster-demo_trk-ex-back-tier
      - trickster-demo_trk-ex-front-tier
    restart: always
    ports:
      - 3002:3000

networks:
  trickster-demo_trk-ex-front-tier:
    external: true
  trickster-demo_trk-ex-back-tier:
    external: true
