version: '3.8'
services:

  # Metrics
  # ============================================================================
  # Grafana
  grafana-redis:
    image: grafana/grafana:6.7.3
    container_name: trickster-grafana-redis
    restart: always
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./docker/grafana/redis/grafana-config:/etc/grafana
      - ./docker/grafana/redis/dashboards:/var/lib/grafana/dashboards
    networks:
      - trk-ex-front-tier
      - trk-ex-back-tier
    ports:
      - 3000:3000

  # Proxy
  # ============================================================================
  # Trickster
  trickster:
    image: tricksterproxy/trickster:1.1.0-beta
    container_name: trickster-server-redis
    restart: always
    depends_on:
      - grafana-redis
      - redis
    volumes:
      - ./docker/trickster-config/redis:/etc/trickster
      - ./docker/trickster-data/redis:/data/trickster
    networks:
      - trk-ex-back-tier
    ports:
      - 8480:8480   # primary frontend proxy port (insecure)
      - 8481:8481   # metrics port (insecure)
      # - 8483:8483 # tls frontend proxy port, unused in this demo
      - 8484:8484   # config reload port (insecure), exposed publicly for demonstration purposes only

  # Redis
  redis:
    image: redis:latest
    container_name: trickster-redis
    restart: always
    user: nobody
    networks:
      - trk-ex-back-tier
    ports:
      - 6379:6379

networks:
  trk-ex-front-tier:
    external: true
  trk-ex-back-tier:
    external: true
