version: '3.8'
services:

  # Metrics
  # ============================================================================
  # Grafana
  grafana-fs:
    image: grafana/grafana:6.7.3
    container_name: trickster-grafana-fs
    restart: always
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./docker/grafana/fs/grafana-config:/etc/grafana
      - ./docker/grafana/fs/dashboards:/var/lib/grafana/dashboards
    networks:
      - trk-ex-front-tier
      - trk-ex-back-tier
    ports:
      - 3000:3000

  # Proxy
  # ============================================================================
  # Trickster
  trickster:
    image: tricksterproxy/trickster:1.1.0-beta
    container_name: trickster-server-fs
    restart: always
    depends_on:
      - grafana-fs
    volumes:
      - ./docker/trickster-config/fs:/etc/trickster
      - ./docker/trickster-data/fs:/data/trickster
    networks:
      - trk-ex-back-tier
    ports:
      - 8480:8480   # primary frontend proxy port (insecure)
      - 8481:8481   # metrics port (insecure)
      # - 8483:8483 # tls frontend proxy port, unused in this demo
      - 8484:8484   # config reload port (insecure), exposed publicly for demonstration purposes only

networks:
  trk-ex-front-tier:
    external: true
  trk-ex-back-tier:
    external: true
