# config file version
apiVersion: 1

datasources:
# InfluxDB - trickster - Memory
- name: influx-trickster-mem
  type: influxdb
  access: proxy
  orgId: 1
  url: http://trickster:8480/influx1
  password:
  user:
  database: inspectit
  basicAuth:
  basicAuthUser:
  basicAuthPassword:
  withCredentials:
  isDefault:
  secureJsonData:
    tlsCACert: "..."
    tlsClientCert: "..."
    tlsClientKey: "..."
  version: 1
  editable: false
