# config file version
apiVersion: 1

datasources:
# InfluxDB
- name: influx-direct
  type: influxdb
  access: proxy
  orgId: 1
  url: http://influxdb-server:8086
  password:
  user:
  database: inspectit
  basicAuth:
  basicAuthUser:
  basicAuthPassword:
  withCredentials:
  isDefault:
  secureJsonData:
    tlsCACert: "..."
    tlsClientCert: "..."
    tlsClientKey: "..."
  version: 1
  editable: false
